# Stage One: Compile & Publish
FROM microsoft/aspnetcore-build
# RUN echo "hello world" | tee greeting.txt
VOLUME /SpamREST
WORKDIR /SpamREST
EXPOSE 80/tcp
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENTRYPOINT dotnet restore \
  && dotnet watch run --environment=Development