# Stage One: Compile & Publish
FROM microsoft/aspnetcore-build AS builder
WORKDIR /SpamREST
COPY ./SpamREST/*.csproj .
RUN dotnet restore
COPY ./SpamREST/ .
RUN dotnet run --output /app/ --environment=Development

# Stage Two: Run
FROM microsoft/aspnetcore
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "SpamREST.dll"]

# Run example:  docker run -it -p 5000:80 spamrest